### ISSUE TITLE
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "metadata"

### ISSUE THREAD

**Issue by KaiSuchomel** [quarkiverse/quarkus-openfga-client#171]
During the write of a Tuple into the OpenFGA Server the following Exception occurs:

```
java.util.concurrent.CompletionException: 
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "metadata" (class io.quarkiverse.openfga.client.model.Condition), not marked as ignorable (3 known properties: "expression", "parameters", "name"])
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 1818] (through reference chain: io.quarkiverse.openfga.client.model.dto.ListAuthorizationModelsResponse["authorization_models"]->java.util.ArrayList[0]->io.quarkiverse.openfga.client.model.AuthorizationModel["conditions"]->java.util.LinkedHashMap["samePlant"]->io.quarkiverse.openfga.client.model.Condition["metadata"])
	at io.smallrye.mutiny.operators.uni.UniBlockingAwait.await(UniBlockingAwait.java:79)
	at io.smallrye.mutiny.groups.UniAwait.atMost(UniAwait.java:65)
	at io.smallrye.mutiny.groups.UniAwait.indefinitely(UniAwait.java:46)
	at io.GreetingResourceTest.shouldDoOpenFGA(GreetingResourceTest.java:50)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
```

I have created a small reproducer project under: [quarkus-openfga](https://github.com/KaiSuchomel/quarkus-openfga)
execute GreetingResourceTest:shouldDoOpenFGA

The underlying model contains a condition:

```yaml
model
  schema 1.1

type user

type plant
    
type asset-category
    relations
        define read: [role#assignee with samePlant] or update
        define update: [role#assignee with samePlant] or create
        define create: [role#assignee with samePlant] or delete
        define delete: [role#assignee with samePlant]
        define release: [role#assignee with samePlant]

type role
    relations
        define assignee: [user]
      
condition samePlant(plantA: string, plantB: string) {
    plantA == plantB
}
```

**Comment by ahrens-lgln** [comment]
We can confirm this issue and currently use the commit proposed in #181 to work around it.
